### ISSUE TITLE
When will you update the code?

### ISSUE THREAD

**Issue by Cppowboy** [lixin4ever/TNet#1]
Where is the code?

**Comment by lixin4ever** [comment]
@Cppowboy Thanks for your attention.

The code has not been cleaned since I am preparing my Ph.D. qualifying exam these days and don't have time to do it.

Expected online date of our code is in early June, please stay tuned.

**Comment by dengyuning** [comment]
When will you release your code?

**Comment by km1994** [comment]
When will you release your code?

**Comment by lixin4ever** [comment]
@km1994 Please give me your email address so that I can send you the code via email.

**Comment by clairett** [comment]
Same question, when will you release your code?

**Comment by bryant03** [comment]
Hi,can you send the code via email to bryants03@163.com,please.I am also very interested in this research field. Thank you!

**Comment by lixin4ever** [comment]
Hello everyone, if you need our code for research purpose, do not hesitate to drop me an email.  

Also, if the code is useful for your projects, please star this repo and cite our ACL paper.

**Comment by MatildaX** [comment]
Hi, I'm working on another field, and find some ideas in your work might help. Can you send your code to himatilda@163.com? Thanks a lot!

**Comment by lixin4ever** [comment]
@MatildaX Sent

**Comment by DrJZhou** [comment]
Hi, I am interested in this research field, and can you send your code to 1633636038@qq.com? Thanks a lot!

**Comment by lixin4ever** [comment]
@12190143 Sent

**Comment by daiw10** [comment]
Hi,can you send your code to daiw01518385@163.com . I am also very interested in your research. Many thanks!

**Comment by lixin4ever** [comment]
@daiw10 Sent

**Comment by xymcsu** [comment]
Hi,can you send your code to xymcsu@foxmail.com . I am also very interested in your research. Many thanks!

**Comment by lixin4ever** [comment]
@xymcsu Sent

**Comment by nadaxgo** [comment]
340440056@qq.com     3Q3Q

**Comment by km1994** [comment]
Hi,can you send your code to 13484276267@163.com . I am also very interested in your research. Many thanks!

**Comment by chosenone75** [comment]
Hi, well-written paper and nice work !!!  I am also very interested in ABSA, could  I get a copy of your complete source code to reproduce your work, my E-mail is lebronran@gmail.com , thanks a lot.

**Comment by lixin4ever** [comment]
@nadaxgo @km1994 @chosenone75  Sent

**Comment by lixin4ever** [comment]
Thanks @12190143 to help me to fix the bug in the code, which is critical to the classification performance. If you guys still have any problems, feel free to contact me.

**Comment by ipp123456** [comment]
359890642@qq.com  thank you for sharing.

**Comment by FallingSlowly** [comment]
@lixin4ever Hi, would you mind to send the code to njautravis@gmail.com? I've read your paper and it is a nice work!

**Comment by lixin4ever** [comment]
@FallingSlowly Sent

**Comment by yunyunandruirui** [comment]
Hi, I 'm interested in this research field, and would you mind to send your code to xxyun_yun@163.com? Thanks a lot!

**Comment by catjuting** [comment]
Hi,can you share your code to me. I am also very interested in your research. This is my email, 1130729577@qq.com. Thanks a lot!

**Comment by YiLing28** [comment]
DavidLingM@163.com,Thanks a lot!

**Comment by lixin4ever** [comment]
@catjuting @lingdavid  I will send the code to you as soon as possible.

**Comment by Jorigorn** [comment]
@lixin4ever  Hi, please send me one jorligorn@gmail.com 

Thanks a lot. :)

**Comment by lixin4ever** [comment]
@catjuting @lingdavid @Jorigorn Sent

**Comment by zgdzgdzgd** [comment]
I am a student and I am also very interested in your research,can you send your code to 863691914@qq.com please,thanks.

**Comment by lixin4ever** [comment]
@zgdzgdzgd Sent

**Comment by ghost** [comment]
I am a student and I am interested in your paper. Could you please send me your code implementation to daxintan@gmail.com? Thank you a lot! By the way, may I know how long is the ordinary training time of this model?

**Comment by lixin4ever** [comment]
@DaxinTan Sent

**Comment by yufuin** [comment]
Hi, I am interested in your paper. Could you send me your code?
yufuinian@gmail.com
Thanks a lot.

**Comment by lixin4ever** [comment]
@yufuinn Sent

**Comment by nanguoshun** [comment]
@lixin4ever , dear Lixin, would you please share your code, my email address is:  nanguoshun@gmail.com,  thanks a lot!

**Comment by lixin4ever** [comment]
@nanguoshun Sent

**Comment by refuoe** [comment]
@lixin4ever Hi Lixin, may you kindly share your code with me at refuoemokhosi@yahoo.com. Thanks!

**Comment by lixin4ever** [comment]
@refuoe Sent

**Comment by lizekang** [comment]
@lixin4ever Hi, Lixin, I'm very interested in your paper, could you send me your code at zekangli97@gmail.com? Thanks a lot!

**Comment by lixin4ever** [comment]
@lizekang Sent

**Comment by WadeYin9712** [comment]
@lixin4ever Hi, Lixin, I'm very interested in your paper, could you send me your code at 814090890@qq.com? Thanks!

**Comment by YanghangXu** [comment]
@lixin4ever Hi, Lixin, I'm very interested in your paper, could you send me your code at 1366287975@qq.com? Thanks!

**Comment by JHWen** [comment]
Hello,Lixin. I am very interested in your paper.Could you send me your code at 1940098534@qq.com? Thank you very much!

**Comment by lixin4ever** [comment]
@WadeYin9712 @YanghangXu @JHWen Sent

**Comment by XiandaGuo** [comment]
Hello,Lixin. I am very interested in your paper.Could you send me your code at xianda_guo@163.com? Thanks!

**Comment by lixin4ever** [comment]
@guoxianda Sent

**Comment by zhouchx** [comment]
Hello,Lixin. I am very interested in your paper.Could you send me your code at zhouchx9@mail2.sysu.edu.cn? Thank you so much!

**Comment by ThiagoSousa** [comment]
Hi! Do you mind sharing the code, please? My email is thiagosousasilveira@gmail.com. 

Thank you very much!

**Comment by LiuChiachi** [comment]
Hi, Lixin. I am new to this research field and interested in sentiment recognition, and can you send your code to me? My E-mail address is liujiaqi.it@gmail.com. Thanks a lot!

**Comment by Echoyyyy** [comment]
Hi, Lixin, i am doing this research, and Could you send your code to my mail echo_yang@bupt.edu.cn?Please. Thanks a lot.

**Comment by lixin4ever** [comment]
@zhouchx @ThiagoSousa @LiuChiachi @Echoyyyy Sent

**Comment by karencceeee** [comment]
Hi, Lixin, Could you send your code to my mail chenchen.karen@gmail.com? thanks a lot.

**Comment by lixin4ever** [comment]
@karencceeee Sent

**Comment by codesoftwind** [comment]
Hi, Lixin, I'm very interested in your paper. Could you please send your code to my email liupsoftwind@163.com? thank you very much!

**Comment by Imorton-zd** [comment]
@lixin4ever Would you please share your code, my email address is: dzhangsuda@qq.com, thanks a lot!

**Comment by redinton** [comment]
@lixin4ever  Hi,LiXin, your team's work is really amazing, would you please send me your code via jason961217@gmail.com thanks again!

**Comment by jiangtaojy** [comment]
@lixin4ever i'm very interested in your paper, could you please send your code to my email?my email address is: jiangt59@mail2.sysu.edu.cn, thanks a lot!

**Comment by SherryShen9** [comment]
@lixin4ever. Hi, Lixin, i am a student and doing this research. Could you please send your code to my mail @1403195437@qq.com? Please. Thanks a lot.

**Comment by Clitost** [comment]
@lixin4ever  Hi.Lixin.I am very  interested in your network,could you please send your code to my mail 
632127161@qq.com.Thank you so much!

**Comment by lixin4ever** [comment]
@monsterspeaking @syl007 @Clitost Sent

**Comment by GeneZC** [comment]
@lixin4ever Could you please send your code to my email [gene_zhangchen@163.com](url) for research use? Thanks in advance!

**Comment by lixin4ever** [comment]
@lixin4ever Sent

**Comment by MasterFishfish** [comment]
@lixin4ever hello,  i am a student and I am very interested in your network! Could you please send your code to my email tusimplefishfish@foxmail.com? Thank you very much

**Comment by lixin4ever** [comment]
@MasterFishfish Sent

**Comment by mojave-pku** [comment]
@lixin4ever hello, could you please send me your code to my email hlz@pku.edu.cn for research use? Thanks a lot.

**Comment by BigHeartC** [comment]
@lixin4ever  hi~, could you please send me your code to my email bigheart_c@163.com for research use? Thanks very much!

**Comment by lixin4ever** [comment]
@HuangLianzhe @BigHeartC Sent

**Comment by nan0606** [comment]
@lixin4ever 
hi~, I'm a student and doing this research. Could you send your code to my mail qiannan_xu@163.com. Thank you very much!

**Comment by lixin4ever** [comment]
@nan0606 Sent

**Comment by r05323028** [comment]
@lixin4ever hello, I'm interesting in aspect-level sentiment analysis recently and found that you have this amazing work! could you please send your code to my mail r05323028@ntu.edu.tw. Thanks!

**Comment by a3226672** [comment]
Hi, Lixin, Could you send your code to my email 372178827@qq.com? Thank you very much!

**Comment by lixin4ever** [comment]
@r05323028 @a3226672 Sent

**Comment by Pro0Izzie** [comment]
@lixin4ever Hi, I'm doing some research on aspect-based sentiment analysis. Could you send your code to my mailbox im.izzie.yu@gmail.com? Thank you very much.

**Comment by lixin4ever** [comment]
@Pro0Izzie Sent

**Comment by guoyan1996** [comment]
Hi,can you send your code to 1028109394@qq.com. I am also very interested in your research. Many thanks!

**Comment by ghost** [comment]
hi @lixin4ever   
I am self-study emotional analysis and would like to learn about your code. Can you send me a copy?
swdailh@gmail.com
thank you very much.

**Comment by lixin4ever** [comment]
@guoyan1996 @ccnankai Sent

**Comment by daisy654** [comment]
Hi,can you share your code to me. I am also very interested in your research. This is my email, shgrcr@163.com. Thanks a lot!

**Comment by ghost** [comment]
@lixin4ever   Thank you very much

**Comment by wusx00** [comment]
Hi, could you please share your code with me? I'm interested in your research and hope to know more details about it. Thank you very much !
My email is sixingwu@outlook.com

**Comment by r05323028** [comment]
hello everyone,
this is the TNet tensorflow version which is implemented by me, but it still has some problems and can't reach the reported results. Could someone give me some suggestions?
https://github.com/r05323028/TNet-tensorflow

**Comment by r05323028** [comment]
> hello everyone,
> this is the TNet tensorflow version which is implemented by me, but it still has some problems and can't reach the reported results. Could someone give me some suggestions?
> https://github.com/r05323028/TNet-tensorflow

Okay, I found the problem by myself... I forget shuffle on each epoch lol

**Comment by liangtianxin** [comment]
154069247@qq.com  thank you so much.

**Comment by lixin4ever** [comment]
@liangtianxin Sent

**Comment by apmoore1** [comment]
Hi,
Would it be possible to get a copy of the code:
andrew.p.moore94@gmail.com

Thanks,
Andrew.

**Comment by 1973Blunt** [comment]
hi @lixin4ever. Can you send me the code? My email is 913247579@qq.com.

**Comment by BigFaceWangCY** [comment]
Hi,can you send your code to [weizhaojing@outlook.com](mailto:weizhaojing@outlook.com) . I am also very interested in your research. Many thanks!

**Comment by liaoyulei** [comment]
Hi, can you send me your code? My email is lyulei@126.com. Thank you very much!

**Comment by htlAllen** [comment]
Hello, i feel so sorry to bother you. But i really interested in your research and hope get further understanding by reading your code. email: yyisawesome@163.com . thank you

**Comment by lixin4ever** [comment]
@1973Blunt @BigFaceWangCY @liaoyulei @htlAllen Sent

**Comment by qq740379** [comment]
Hello, I'm sorry to bother you, could you send me your code for improving my reading of your article,Thanks
my email:740379775@qq.com

**Comment by jepyh** [comment]
For ABSA result comparison. 417191043@qq.com Thx.

**Comment by beihangwenbin** [comment]
Hello,I want to get your code for research! There is my e-mail:1326407080@qq.com,thanks.

**Comment by lixin4ever** [comment]
@qq740379 @jepyh @beihangwenbin Sent

**Comment by CodeWithCat** [comment]
hello,can u send your code to me ? im really interest in  your research  and i wang to have a try,thank you
email: nlpdreamer2018@gmail.com

**Comment by lixin4ever** [comment]
@nlpdestiny Sent

**Comment by ksyash** [comment]
Hi, Li Xin. Could you please share your code, i am currently exploring possibilities for aspect based analysis, my email: o_kachaniuk@hotmail.com  Thank you in advance

**Comment by lixin4ever** [comment]
@ksyash Sent

**Comment by blue772001** [comment]
Hello, Could you send me your source code? 
my email is blue772001@gmail.com 
Thank you in advance.

**Comment by oldstree** [comment]
Hi,Li Xin,Could you please share you code, my email: chengshiwen@mail.nwpu.edu.cn ,Thank you in advance

**Comment by lixin4ever** [comment]
@blue772001 @oldstree Sent

**Comment by oldstree** [comment]
Thanks

**Comment by blue772001** [comment]
Thank you a lot.

2019년 3월 27일 (수) 오후 11:03, rabbit <notifications@github.com>님이 작성:

**Comment by WanphiaYu** [comment]
Hi, Li Xin. Could you please share your code, i am currently exploring possibilities for user preference analysis, my email: 386899284@qq.com    Thank you in advance

**Comment by tyj1997** [comment]
305099672@qq.com thanks!

**Comment by lixin4ever** [comment]
@WanphiaYu @tyj1997 Sent

**Comment by Bogerchen** [comment]
Thanks for your impressive work! Could you please send me your code for further research? My email is chenchb7@mail2.sysu.edu.cn . Thanks a lot!

**Comment by weihuiHong** [comment]
Could you please share you code? I am also very interested in your research. My email: weihui_Hong@outlook.com . Thanks!

**Comment by yuanmingchen** [comment]
你好，我最近在做相关研究，可以把代码发给我吗，我的邮箱是：mcyuan@ir.hit.edu.cn。谢谢！

**Comment by weihuiHong** [comment]
你好，作者目前还没有发代码给我，如果你手边已经有了这份代码，可不可以发给我一份

发件人: yuanmc <notifications@github.com>
答复: lixin4ever/TNet <reply@reply.github.com>
日期: 2019年4月9日 星期二 12:47
收件人: lixin4ever/TNet <TNet@noreply.github.com>
抄送: weihuiHong <weihui_Hong@outlook.com>, Comment <comment@noreply.github.com>
主题: Re: [lixin4ever/TNet] When will you update the code? (#1)


你好，我最近在做相关研究，可以把代码发给我吗，我的邮箱是：mcyuan@ir.hit.edu.cn<mailto:mcyuan@ir.hit.edu.cn>。谢谢！

**Comment by lixin4ever** [comment]
@Bogerchen @weihuiHong @yuanmingchen Sent

**Comment by Bogerchen** [comment]
Thank you very much!

**Comment by mmollayi** [comment]
cyrus.yazdgerd3@gmail.com Thanks in advance.

**Comment by mahdiipm** [comment]
very impressive work. could you please send me the code ? 
mahdi.ipm98@gmail.com

**Comment by venusafroid** [comment]
Hi, I am interested in this research field, and can you send your code to h_n_ing@163.com? Thanks a lot!

**Comment by lixin4ever** [comment]
@mahdiipm @venusafroid Sent

**Comment by liyuwe** [comment]
Hi， I am a student who is busy in graduation design work and I sincerely hope that you could send your code to liyuwei513@163.com. Thank you very much!

**Comment by finn-verse** [comment]
Hey, Li Xin. Would you please share your code with me. I am very interested in your work. Thank you in advance!

**Comment by lixin4ever** [comment]
@liyuwe @Finnism Sent

**Comment by finn-verse** [comment]
Thanks!

**Comment by liyuwe** [comment]
Thank you very much!

**Comment by anonymous4review5** [comment]
Hi,can you send your code to 413954551@qq.com . I am also very interested in your research. Many thanks!

**Comment by Raphael95** [comment]
@lixin4ever, it's a pleasant work，could you please send me the code? Raphael-95@outlook.com, thanks a lot

**Comment by lixin4ever** [comment]
@myforever @Raphael95 Sent

**Comment by HaopengZhang96** [comment]
Hi，Would you please share your code with me.. I have stared your repo. My email zhanghaopeng96@163.com, I also sent an email to your cuhk email.

**Comment by lixin4ever** [comment]
@HaopengZhang96 Sent

**Comment by SizzleWang** [comment]
hi  I am a student who is interested in your reserch. Can you send your code to ascendswang@gmail.com. Thank you!

**Comment by lixin4ever** [comment]
@SizzleWang Sent

**Comment by SizzleWang** [comment]
Thank you！

**Comment by Angelinaa** [comment]
hi, Li Xin. I am a student interested in your research. Can you send your code to 911319433@qq.com? Thank you very much!

**Comment by lixin4ever** [comment]
@Angelinaa Sent

**Comment by 9ayhub** [comment]
Could you show me the code？My email is 354787627@qq.com，thanks！

**Comment by lixin4ever** [comment]
@9ayhub Sent

**Comment by moon1314** [comment]
Hello, I am a student interested in your research, could you send the code to me please?My Email is illidanying@163.com, thank you!

**Comment by lixin4ever** [comment]
@moon1314 Sent

**Comment by Determined22** [comment]
Hi Xin Li, 
I'd like to know some implementation details about TNet. Could you share the code with me? 
My email: weipenghui2016@ia.ac.cn

Thanks.

**Comment by lixin4ever** [comment]
@Determined22 Sent

**Comment by cjw245929674** [comment]
Hello, Xin Li,
I am a student, I am very interested in your paper. Could you share the code with me?
My email: 245929674@qq.com
Thanks.

**Comment by hiyouga** [comment]
Hello, I am interested in your research, could I request your code for personal research? Thanks! My email: 467089858@qq.com

**Comment by lixin4ever** [comment]
@cjw245929674 @hiyouga Sent

**Comment by hellozjj** [comment]
can you send your code to 1720500091@qq.com  please,thanks.

**Comment by Italian-PAO** [comment]
1410430449@qq.com thank you so much

**Comment by Hongze-Wang** [comment]
Hi, can u send a copy of your code to wanghongzecn@qq.com, thanks a lot.

**Comment by lixin4ever** [comment]
@Hongze-Wang Sent

**Comment by zthhao** [comment]
Hi, i'm a student interested in your research, can you sent your code to 308573239@qq.com, thanks a lot.

**Comment by lixin4ever** [comment]
@zthhao Sent

**Comment by zthhao** [comment]
Thank you

**Comment by logoutAgain** [comment]
Hi, I am interested in your study. Can u send me your code? 519941624@qq.com  thx!

**Comment by lixin4ever** [comment]
@liangzihong Sent

**Comment by freesunshine0316** [comment]
Code? freesunshine0316@gmail.com

**Comment by lixin4ever** [comment]
@freesunshine0316 Sent
