### ISSUE TITLE
Can you  share your code ：mengmengcui915@gmail.com?

### ISSUE THREAD

**Issue by CMM915915** [lixin4ever/TNet#20]
Can you  provide your code about your paper?I am very  grateful  for your contribution.I like  sentiment analysis  very much .

**Comment by CMM915915** [comment]
Thank you  very much.

**Comment by lixin4ever** [comment]
Hello

Is "CMM915915@gmail.com" a valid email address? I try to send the email to you but the delivery failed.

**Comment by CMM915915** [comment]
> Hello
> 
> Is "[CMM915915@gmail.com](mailto:CMM915915@gmail.com)" a valid email address? I try to send the email to you but the delivery failed.
sorry,it s not mine,my email  is  mengmengcui915@gmail.com.I have  just  wrote  it wrong.can  you  send again?

**Comment by lixin4ever** [comment]
Sent.
