### ISSUE TITLE
code

### ISSUE THREAD

**Issue by NaitangTian** [lixin4ever/TNet#5]
Hello,can you share your code to me. I am very interested in your research. This is my email, 719771993@qq.com. Thank you very much!!!

**Comment by lixin4ever** [comment]
@NaitangTian Sent

**Comment by AnqiLeee** [comment]
hello! i'm also very interested in this paper. could you please share your code to me? my email is 260752732@qq.com . THANKS!! :)

**Comment by skywindy** [comment]
Hello! i'm also very interested in this paper and the idea,and I want to try it with my data.  could you please share your code with me? my email is 760201005@qq.com . Thanks very much.

**Comment by lixin4ever** [comment]
@AnqiLeee @skywindy Sent
