### ISSUE TITLE
why add the convolution layer?

### ISSUE THREAD

**Issue by YHTtTtao** [lixin4ever/TNet#9]
LSTM can already capture the position information，why you add a position-aware convolution layer？

**Comment by lixin4ever** [comment]
Here, the position information refers to the position relevance between the current hidden representation and the given aspect/target representation. LSTM can indeed capture the target-specific position information in an implicit way (i.e., closer (to the target) is more important). Our design is to explicitly incorporate such information into the convolutional feature extractor.

**Comment by YHTtTtao** [comment]
Thank you for your answer! I want to add the calss of Absolute_Position_Embedding and the for recurrent part in my module，and I added them after the lstm and attention，but I got the Value Error:expected sequence of length 7 at dim1(got 1),how can I handle it?
